---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.21.3-bullseye

inputs:
  - name: dp-jaeger-tracing

outputs:
  - name: build

run:
  path: dp-jaeger-tracing/ci/scripts/build.sh
